// <auto-generated />
using System;
using FortunaDigital.Infraistructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FortunaDigital.Infraistructure.Migrations
{
    [DbContext(typeof(FortunaDigitalDbContext))]
    [Migration("20231013190650_AddActiveColumnRaffleTable")]
    partial class AddActiveColumnRaffleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FortunaDigital.Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdRaffleNumber")
                        .HasColumnType("char(36)");

                    b.Property<int>("Paid")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("PaymentLink")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PaymentMethod")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("PixCode")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<float>("TotalValue")
                        .HasColumnType("float(7,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FortunaDigital.Core.Entities.Raffle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Active")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Level")
                        .HasColumnType("int(1)");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalByNumber")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Raffles");
                });

            modelBuilder.Entity("FortunaDigital.Core.Entities.RaffleNumbers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdPayment")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdRaffle")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdPayment")
                        .IsUnique();

                    b.HasIndex("IdRaffle");

                    b.HasIndex("IdUser");

                    b.ToTable("RaffleNumbers");
                });

            modelBuilder.Entity("FortunaDigital.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int(2)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FortunaDigital.Core.Entities.RaffleNumbers", b =>
                {
                    b.HasOne("FortunaDigital.Core.Entities.Payment", "Payment")
                        .WithOne("RaffleNumber")
                        .HasForeignKey("FortunaDigital.Core.Entities.RaffleNumbers", "IdPayment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FortunaDigital.Core.Entities.Raffle", "Raffle")
                        .WithMany("RaffleNumbers")
                        .HasForeignKey("IdRaffle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FortunaDigital.Core.Entities.User", "User")
                        .WithMany("RaffleNumbers")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Raffle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FortunaDigital.Core.Entities.Payment", b =>
                {
                    b.Navigation("RaffleNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("FortunaDigital.Core.Entities.Raffle", b =>
                {
                    b.Navigation("RaffleNumbers");
                });

            modelBuilder.Entity("FortunaDigital.Core.Entities.User", b =>
                {
                    b.Navigation("RaffleNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
